name: AutoTrigger

on:
  workflow_dispatch:
  schedule:
    - cron: '30 */2 * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Init
      run: |
        nslookup gitee.com
        echo "===================================="
        sudo echo "nameserver 8.8.8.8" > /etc/resolv.conf
        nslookup gitee.com
        echo "===================================="
        dig @8.8.8.8 gitee.com

    - name: AutoTrigger
      uses: bigbugcc/ActionBot@main

    - name: Delete workflow runs
      uses: bigbugcc/delete-workflow-runs@main
      with:
        keep_minimum_runs: 2

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 4
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}